### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by henribru**

### CODE REVIEW

**Comment by s0lvang** [comment]
Thank you for the contribution! 

I'm not a collaborator on this project, but i have contacted the one who is.

**Comment by zootos** [comment]
Does not work out of the box for me on MacOS. I have changed all group `XX` numbers in the configuration files, and even ran `chmod +x docker-entrypoint.sh`, however I am still getting the following error. And clue why?

```bash
Starting sourcecopy_nginx_1 ... 
Starting sourcecopy_sec_1 ... done
Attaching to sourcecopy_nginx_1, sourcecopy_sec_1
sec_1    | /bin/sh: 1: ./docker-entrypoint.sh: Permission denied
sourcecopy_sec_1 exited with code 126
```

**Comment by henribru** [comment]
@zootos Looks like the executable bit was getting unset, possibly because of the stuff I did to make things work even when the repo is checked out with Windows line endings. I'm explicitly setting it in the Dockerfile now, could you see if that helps?

**Comment by zootos** [comment]
@henribru It runs now. However, the docker process does not seem to expose any ports.

**Comment by henribru** [comment]
@zootos Well, it's running in host mode, so it shouldn't have to (I did it this way to avoid having to change the address in the Nginx config). I don't know if it works differently on Mac, but I can reach the application on localhost both on Windows and Linux.

**Comment by henribru** [comment]
Ok so apparently host mode doesn't work on Mac: https://github.com/docker/for-mac/issues/2716 (or on Windows unless you're running Docker Toolbox which I happen to be doing). I can use the normal mode instead and expose the ports. Note that in that case the hostname in the Nginx config will have to be changed before you guys deploy a group's code to the server.

**Comment by henribru** [comment]
@zootos Should be fixed now

**Comment by zootos** [comment]
@henribru Works now

**Pull request merged**
